fix  bug causing the following RuntimeError   when call apply_weights with bias tensor
 vllm/model_executor/layers/linear.py", line 70, in apply_weights
    if bias:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous